#!/usr/bin/env python3
"""Generate (or validate) the derived blog artifacts from each post's frontmatter.

Three outputs, all rebuilt from the posts on every push to main (see
.github/workflows/generate-blog.yml), so contributors never edit them by hand:

    blog/posts/index.json   what blog.html fetches to build the card grid
    sitemap.xml             one <url> per post, so search engines can find them
    blog.html               the same cards as real <a href> links in the markup

The last two exist because the card grid is built client-side. Without them a
post is reachable only by executing JavaScript and is absent from the sitemap,
so nothing links to it and nothing lists it — which is how the whole blog
stayed unindexed. The static cards are the initial content of #post-list; the
grid script replaces them on load, so JS and no-JS readers see the same posts
at the same URLs.

The same script runs in --check mode on pull requests to validate a post's
frontmatter and filename before merge.

Posts are ordered pinned-first, then by the displayed `date`, then by when the
post landed on main (merge order) so same-day posts sort newest-merged-first
automatically — see merge_ts(). That tiebreaker needs git history, so the
workflow checks out with fetch-depth: 0.

Usage:
    python3 scripts/generate_blog_index.py            # write all three outputs
    python3 scripts/generate_blog_index.py --check    # validate only, write nothing
"""

from __future__ import annotations

import html
import json
import re
import subprocess
import sys
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
POSTS_DIR = ROOT / "blog" / "posts"
INDEX_PATH = POSTS_DIR / "index.json"
SITEMAP_PATH = ROOT / "sitemap.xml"
BLOG_PAGE_PATH = ROOT / "blog.html"

SITE = "https://leapps.org"

# Generated regions, rewritten in place between these exact marker lines. The
# indentation is part of the marker so the surrounding file stays tidy.
SITEMAP_BEGIN = "  <!-- BEGIN blog posts (generated by scripts/generate_blog_index.py) -->"
SITEMAP_END = "  <!-- END blog posts -->"
CARDS_BEGIN = "      <!-- BEGIN post cards (generated by scripts/generate_blog_index.py) -->"
CARDS_END = "      <!-- END post cards -->"

MONTHS = ("January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December")

FRONTMATTER_RE = re.compile(r"^---\s*\n(?P<body>.*?)\n---\s*", re.DOTALL)
SLUG_RE = re.compile(r"^[\w-]+$")            # exactly what worker.js accepts
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
REQUIRED_FIELDS = ("title", "date", "author", "tags", "excerpt")


def parse_scalar(value: str):
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
        return value[1:-1]
    if value.lower() == "true":
        return True
    if value.lower() == "false":
        return False
    return value


def parse_value(value: str):
    value = value.strip()
    if value.startswith("[") and value.endswith("]"):
        inner = value[1:-1].strip()
        return [parse_scalar(part) for part in inner.split(",")] if inner else []
    return parse_scalar(value)


def parse_frontmatter(markdown: str):
    match = FRONTMATTER_RE.match(markdown)
    if not match:
        return None
    metadata = {}
    for line in match.group("body").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, sep, value = line.partition(":")
        if not sep:
            continue
        metadata[key.strip()] = parse_value(value)
    return metadata


def is_real_date(value) -> bool:
    if not isinstance(value, str) or not DATE_RE.match(value):
        return False
    try:
        from datetime import date
        date.fromisoformat(value)
        return True
    except ValueError:
        return False


def validate(path: Path, meta, errors: list, warnings: list) -> None:
    """Collect errors/warnings for one post. `path` names it in messages."""
    slug = path.stem
    if not SLUG_RE.match(slug):
        errors.append(f"{path.name}: filename/slug is not URL-safe — use only letters, digits, hyphen, underscore.")
    if re.search(r"[A-Z]", slug):
        warnings.append(f"{path.name}: slug has uppercase letters; lowercase is recommended for URLs.")

    if meta is None:
        errors.append(f"{path.name}: missing YAML frontmatter (--- block at the top).")
        return

    for field in REQUIRED_FIELDS:
        val = meta.get(field)
        if val is None or (isinstance(val, str) and not val.strip()):
            errors.append(f"{path.name}: missing required frontmatter field \"{field}\".")

    if "date" in meta and not is_real_date(meta["date"]):
        errors.append(f"{path.name}: date \"{meta.get('date')}\" must be a valid YYYY-MM-DD calendar date.")

    tags = meta.get("tags")
    if tags is not None:
        if not isinstance(tags, list):
            errors.append(f"{path.name}: tags must use inline array syntax, e.g. [iLEAPP, research].")
        elif any(not isinstance(t, str) or not t.strip() for t in tags):
            errors.append(f"{path.name}: every tag must be a non-empty string.")
        elif not tags:
            warnings.append(f"{path.name}: empty tags (the OG card accent falls back to gold).")

    if "pinned" in meta and not isinstance(meta["pinned"], bool):
        errors.append(f"{path.name}: \"pinned\" must be true or false.")

    # Optional: send the mailing-list button somewhere other than the post, for
    # announcements whose real destination is elsewhere (a podcast, a video).
    cta_url = meta.get("cta_url")
    if cta_url is not None:
        if not isinstance(cta_url, str) or not cta_url.strip():
            errors.append(f"{path.name}: \"cta_url\" must be a non-empty URL.")
        elif not re.match(r"^https?://", cta_url.strip()):
            errors.append(f"{path.name}: \"cta_url\" must start with http:// or https:// (got \"{cta_url}\").")
    if "cta_label" in meta:
        label = meta["cta_label"]
        if not isinstance(label, str) or not label.strip():
            errors.append(f"{path.name}: \"cta_label\" must be a non-empty string.")
        elif cta_url is None:
            warnings.append(f"{path.name}: \"cta_label\" has no effect without \"cta_url\".")

    m = re.match(r"^(\d{4}-\d{2}-\d{2})-", slug)
    if m and meta.get("date") and m.group(1) != meta["date"]:
        warnings.append(f"{path.name}: slug date prefix ({m.group(1)}) disagrees with the date field ({meta['date']}).")


def merge_ts(path: Path) -> int:
    """When the post first landed on main, as a Unix timestamp.

    Uses the commit date of the file's add commit on the first-parent (mainline)
    history, so it reflects *merge* order rather than when the contributor
    authored it. Used only as a same-date sort tiebreaker. Returns a large
    sentinel if git history is unavailable (e.g. a new, not-yet-committed post,
    or a shallow clone) so such a post sorts as the newest of its day.
    """
    try:
        rel = str(path.relative_to(ROOT))
        out = subprocess.run(
            ["git", "log", "--first-parent", "--diff-filter=A", "--format=%ct", "--", rel],
            cwd=ROOT, capture_output=True, text=True, check=True,
        ).stdout.split()
        if out:
            return int(out[-1])  # earliest add commit on mainline
    except (subprocess.SubprocessError, ValueError, OSError):
        pass
    return 10 ** 12


def entry(path: Path, meta) -> dict:
    e = {
        "slug": path.stem,
        "title": meta["title"],
        "date": meta["date"],
        "author": meta["author"],
        "tags": meta["tags"],
        "excerpt": meta["excerpt"],
    }
    if meta.get("pinned"):
        e["pinned"] = True
    return e


def post_url(slug: str) -> str:
    """The canonical post URL — must match slugToUrl() in blog.html and the
    canonical the Worker injects, or the sitemap would nominate a different
    URL than the page claims for itself."""
    return f"{SITE}/blog-post?post={quote(slug, safe='')}"


def pretty_date(iso: str) -> str:
    """"2026-07-02" -> "July 2, 2026", matching formatDate() in blog.html.
    Spelled out rather than via strftime so the output can't shift with the
    locale of whatever runner builds the site."""
    from datetime import date
    d = date.fromisoformat(iso)
    return f"{MONTHS[d.month - 1]} {d.day}, {d.year}"


def replace_block(text: str, begin: str, end: str, body: str, name: str) -> str:
    start, stop = text.find(begin), text.find(end)
    if start == -1 or stop == -1 or stop < start:
        raise SystemExit(
            f"{name}: generated block markers missing or out of order — "
            f"expected {begin.strip()} ... {end.strip()}"
        )
    return text[:start] + begin + "\n" + body + text[stop:]


def sitemap_block(posts: list) -> str:
    lines = []
    for p in posts:
        lines += [
            "  <url>",
            f"    <loc>{post_url(p['slug'])}</loc>",
            f"    <lastmod>{p['date']}</lastmod>",
            "    <changefreq>monthly</changefreq>",
            "    <priority>0.7</priority>",
            "  </url>",
        ]
    return "\n".join(lines) + "\n" if lines else ""


def cards_block(posts: list) -> str:
    """The crawlable equivalent of postCard() in blog.html."""
    e = html.escape
    lines = []
    for p in posts:
        author = e(p["author"], quote=True)
        lines += [
            f'      <a class="post-card" href="{e(post_url(p["slug"]), quote=True)}">',
            '        <div class="post-card-meta">',
            f'          <span class="date">{e(pretty_date(p["date"]))}</span>',
            f'          <span class="card-author" data-author="{author}"'
            f' title="More by {author}">{author}</span>',
        ]
        if p.get("pinned"):
            lines.append('          <span class="pin-badge">Pinned</span>')
        lines += [
            '        </div>',
            f'        <h2>{e(p["title"])}</h2>',
            f'        <p>{e(p["excerpt"])}</p>',
        ]
        tags = p.get("tags") or []
        if tags:
            spans = "".join(f'<span class="tag">{e(t)}</span>' for t in tags)
            lines.append(f'        <div class="post-card-tags">{spans}</div>')
        lines.append('      </a>')
    return "\n".join(lines) + "\n" if lines else ""


def write_block(path: Path, begin: str, end: str, body: str, label: str, count: int) -> None:
    original = path.read_text(encoding="utf-8")
    updated = replace_block(original, begin, end, body, path.name)
    if updated != original:
        path.write_text(updated, encoding="utf-8")
    print(f"Wrote {path.relative_to(ROOT)} — {count} {label}.")


def main() -> int:
    check_only = "--check" in sys.argv[1:]

    paths = sorted(POSTS_DIR.glob("*.md"))
    errors: list = []
    warnings: list = []
    parsed = []
    for path in paths:
        meta = parse_frontmatter(path.read_text(encoding="utf-8-sig"))
        validate(path, meta, errors, warnings)
        parsed.append((path, meta))

    for w in warnings:
        print(f"  warning: {w}")
    if errors:
        for e in errors:
            print(f"  error:   {e}", file=sys.stderr)
        print(f"\nBlog frontmatter invalid — {len(errors)} error(s), {len(warnings)} warning(s).", file=sys.stderr)
        return 1

    if check_only:
        print(f"Blog frontmatter valid — {len(parsed)} post(s), {len(warnings)} warning(s).")
        return 0

    # Order: pinned first, then by displayed date, then by when the post landed
    # on main (merge order, newest first); slug is a final stable fallback.
    rows = [(merge_ts(p), entry(p, m)) for p, m in parsed]
    rows.sort(key=lambda r: (bool(r[1].get("pinned")), r[1].get("date", ""), r[0], r[1].get("slug", "")), reverse=True)
    posts = [e for _, e in rows]

    INDEX_PATH.write_text(json.dumps(posts, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {INDEX_PATH.relative_to(ROOT)} — {len(posts)} post(s).")

    write_block(SITEMAP_PATH, SITEMAP_BEGIN, SITEMAP_END,
                sitemap_block(posts), "post URL(s)", len(posts))
    write_block(BLOG_PAGE_PATH, CARDS_BEGIN, CARDS_END,
                cards_block(posts), "crawlable card(s)", len(posts))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
